In [1]:
import numpy as np

Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [64]:
np.flip(np.arange(0,11))

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [65]:
c = np.flip(np.diag(np.arange(7), k=0))
c

array([[6, 0, 0, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [66]:
sum(np.diag(c))

21

Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [4]:
from numpy import linalg

In [13]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4]] )

In [14]:
b = np.array( [4, 12,-3]  )

In [15]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [16]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )


True